name: adote_um_pet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ./design_system

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.4.1
  gap: ^3.0.1
  flutter_masked_text2: ^0.9.1
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  logger: ^2.5.0
  lucid_validation: ^1.1.0
  result_dart: ^2.0.0-alpha.2
  result_command: ^1.0.0-alpha.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_ham.jpeg

